# https://travis-ci.org/jleclanche/python-bna
sudo: false
language: python

python: "3.6"

env:
  - TOXENV=py36
  - TOXENV=flake8
  - TOXENV=mypy

cache: pip

install:
  - pip install tox

script:
  - tox
