[tool.black]
use-tabs = true

[tool.isort]
indent = "tab"
line_length = 88
balanced_wrapping = true
combine_as_imports = true
default_section = "THIRDPARTY"
ensure_newline_before_comments = true
include_trailing_comma = true
known_first_party = ["bna"]
multi_line_output = 3
